version: '2'

services:
  # demo application
  app:
    image: piegsaj/fortune
    command: -w

  web:
    image: nginx
    ports:
      - 8921:80

  # in a multi-host setup you need one instance per host
  logspout:
    image: piegsaj/logspout-logstash
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    restart: unless-stopped
    ports:
      - 8000:80
    links:
      - logstash
    command: logstash://logstash:5000

  logstash:
    image: logstash
    volumes:
      - ./logstash.conf:/etc/logstash.conf
    restart: unless-stopped
    environment:
      LOGSPOUT: ignore
    links:
      - elasticsearch
    command: -f /etc/logstash.conf

  # requires echo "vm.max_map_count=262144" | sudo tee -a /etc/sysctl.conf && sudo sysctl -w vm.max_map_count=262144
  elasticsearch:
    image: elasticsearch:5.0.1
    environment:
      LOGSPOUT: ignore
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    restart: unless-stopped

  kibana:
    image: kibana:5.0.1
    environment:
      LOGSPOUT: ignore
    links:
      - elasticsearch
    ports:
      - 5601:5601
    restart: unless-stopped

volumes:
  elastic_data:
